import { Product } from '@/db/schema';

// Curated authentic initial products for Synapse Engineering & Supply
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    slug: 'hithium-heroee-16-16kwh-lifepo4-battery-pack',
    title: 'HiTHIUM HeroEE 16 — 16kWh LiFePO₄ Portable Battery Pack',
    titleBn: 'হাইথিয়াম হিরো-ইই ১৬ — ১৬ কিলোওয়াট-আওয়ার লিথিয়াম আয়ন ব্যাটারি',
    modelNo: 'HeroEE-16-51.2V-314Ah',
    brand: 'HiTHIUM',
    category: 'Solar & Power Solutions',
    subCategory: 'Lithium / LiFePO4 Energy Storage',
    description: 'Ultra-durable 16kWh LiFePO₄ energy storage system with 11,000+ cycle life. Engineered for factory backup, high-capacity hybrid solar systems, and zero-downtime industrial power continuity in Bangladesh. Equipped with intelligent smart-BMS supporting CAN/RS485 multi-inverter protocol.',
    descriptionBn: '১১,০০০+ সাইকেল লাইফ সমৃদ্ধ ১৬ কিলোওয়াট-আওয়ার হাইথিয়াম লিথিয়াম ফেরো ফসফেট ব্যাটারি প্যাক। ফ্যাক্টরি, কমার্শিয়াল প্রজেক্ট এবং হেভি ডিউটি সোলার পাওয়ার স্টোরেজের জন্য আদর্শ।',
    specs: JSON.stringify({
      'Rated Capacity': '16.08 kWh (51.2V 314Ah)',
      'Battery Chemistry': 'Grade-A LiFePO₄ (Lithium Iron Phosphate)',
      'Cycle Life': '≥ 11,000 Cycles @ 80% DOD',
      'Max Charge / Discharge': '150A / 200A Continuous',
      'Communication': 'CAN / RS485 / RS232 (Supports Deye, Growatt, Megarevo, Sungrow)',
      'Operating Temp': '-10°C to 55°C',
      'Warranty': '10 Years Manufacturer Warranty',
      'Origin': 'Xiamen, China (Direct Factory Dispatch)'
    }),
    price: 0,
    priceType: 'quote',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://synapse-engneering.com/wp-content/uploads/2026/03/HiTHIUM-HeroEE-16.png',
    additionalImages: JSON.stringify([
      'https://synapse-engneering.com/wp-content/uploads/2026/03/HiTHIUM-HeroEE-16-621x800.png'
    ]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'China',
    displayOrder: 1,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  {
    id: 2,
    slug: 'hithium-heroee-maxpower-8-aio-8kwh-solar-system',
    title: 'HiTHIUM MaxPower 8 AIO — 8kWh All-in-One Solar + Battery Backup System',
    titleBn: 'হাইথিয়াম ম্যাক্সপাওয়ার ৮ — অল-ইন-ওয়ান ৮ কিলোওয়াট-আওয়ার সোলার ও ব্যাটারি সিস্টেম',
    modelNo: 'MaxPower-AIO-8k-9000W',
    brand: 'HiTHIUM',
    category: 'Solar & Power Solutions',
    subCategory: 'All-In-One Solar ESS',
    description: 'Integrated 8kWh LiFePO₄ energy storage system with built-in 9000W dual MPPT hybrid inverter. Seamless switchover in <10ms for unnoticeable UPS backup during grid failure. Plug-and-play installation with smartphone app telemetry.',
    descriptionBn: 'বিল্ট-ইন ৯০০০ ওয়াট ডুয়াল MPPT হাইব্রিড ইনভার্টার ও ৮ কিলোওয়াট-আওয়ার লিথিয়াম ব্যাটারি সমন্বিত সম্পূর্ণ কমপ্যাক্ট পাওয়ার সলিউশন। মাত্র ১০ মিলিসেকেন্ডে অটোমেটিক ব্যাকআপ ট্রানজিশন।',
    specs: JSON.stringify({
      'Battery Storage': '8.04 kWh LiFePO₄',
      'Inverter Power': '9000W Pure Sine Wave',
      'MPPT Input': 'Dual MPPT (120V - 500V DC)',
      'Transfer Time': '< 10ms (True UPS Grade)',
      'Parallel Capability': 'Up to 6 units in parallel',
      'Protection': 'IP65 Weatherproof Enclosure',
      'Warranty': '5 Years System Warranty'
    }),
    price: 0,
    priceType: 'quote',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://synapse-engneering.com/wp-content/uploads/2026/03/HiTHIUM-MaxPower-AIO-8-–-Home-Solar-ESS-with-9000W-MPPT-8kWh-Lithium-Battery-2.png',
    additionalImages: JSON.stringify([
      'https://synapse-engneering.com/wp-content/uploads/2026/03/HiTHIUM-MaxPower-8-AIO-–-All-in-One-8kWh-LiFePO₄-Energy-Storage-System-Solar-Grid.png'
    ]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'China',
    displayOrder: 2,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  {
    id: 3,
    slug: 'siemens-s7-1500-6es7532-5hd00-0ab0-analog-output',
    title: 'Siemens SIMATIC S7-1500 6ES7532-5HD00-0AB0 Analog Output Module',
    titleBn: 'সিমেন্স এস৭-১৫০০ অ্যানালগ আউটপুট মডিউল',
    modelNo: '6ES7532-5HD00-0AB0 (AQ 4xU/I ST)',
    brand: 'Siemens',
    category: 'Industrial Automation',
    subCategory: 'PLC Systems & I/O Modules',
    description: 'Original Siemens SIMATIC S7-1500 Analog Output Module with 4 channels for voltage (±10V, 1..5V, 0..10V) and current (±20mA, 0/4..20mA). 16-bit resolution with diagnostics and parameter alarms. Directly sourced and guaranteed authentic from certified distributors in China.',
    descriptionBn: 'অরিজিনাল সিমেন্স S7-1500 অ্যানালগ আউটপুট মডিউল (৪ চ্যানেল, ১৬-বিট রেজোলিউশন)। ইন্ডাস্ট্রিয়াল প্রসেস কন্ট্রোল ও ফ্যাক্টরি অটোমেশনের জন্য শতভাগ জেনুইন ইকুইপমেন্ট।',
    specs: JSON.stringify({
      'Channels': '4 Analog Outputs (Voltage / Current)',
      'Resolution': '16 Bit',
      'Output Ranges Voltage': '±10V, 1-5V, 0-10V',
      'Output Ranges Current': '±20mA, 0-20mA, 4-20mA',
      'Diagnostics': 'Wire break, short circuit, overflow/underflow alarms',
      'Mounting': 'S7-1500 DIN Rail Standard',
      'Authenticity': '100% Genuine with Original Siemens Seal & Serial'
    }),
    price: 0,
    priceType: 'quote',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://synapse-engneering.com/wp-content/uploads/2026/05/siemens-s7-1500-6es7532-5hd00-0ab0-analog-output-276x355.webp',
    additionalImages: JSON.stringify([]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'Germany / China Sourced',
    displayOrder: 3,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  {
    id: 4,
    slug: 'schneider-lc1k06105p7-contactor-6a-230v',
    title: 'Schneider Electric TeSys K LC1K06105P7 Contactor 6A 230V',
    titleBn: 'স্নাইডার ইলেকট্রিক টেসিস কে কন্টাক্টর ৬ অ্যাম্পিয়ার ২৩০ ভোল্ট',
    modelNo: 'LC1K06105P7',
    brand: 'Schneider Electric',
    category: 'Industrial Automation',
    subCategory: 'Contactors & Motor Starters',
    description: 'Compact 3-pole TeSys K contactor rated 6A (AC-3, 440V, 2.2kW) with 230V AC control coil and 1 NO instantaneous auxiliary contact. Ideal for motor control, HVAC equipment, packaging lines, and industrial control panels.',
    descriptionBn: 'স্নাইডার ইলেকট্রিক টেসিস কে ৩-পোল কন্টাক্টর (৬ অ্যাম্পিয়ার, ২৩০V কয়েল)। কন্ট্রোল প্যানেল, মোটর কন্ট্রোল ও ইন্ডাস্ট্রিয়াল সুইচকন্ট্রোলের জন্য দীর্ঘস্থায়ী উপাদান।',
    specs: JSON.stringify({
      'Poles': '3P (3 NO Main Contacts)',
      'Rated Current': '6A (AC-3 @ 440V)',
      'Motor Power': '2.2 kW @ 380/415V AC',
      'Control Circuit Voltage': '230V AC 50/60 Hz',
      'Auxiliary Contacts': '1 NO (Normally Open)',
      'Mechanical Durability': '10 Million Cycles'
    }),
    price: 0,
    priceType: 'quote',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://synapse-engneering.com/wp-content/uploads/2026/05/lc1k1210m7-276x355.webp',
    additionalImages: JSON.stringify([]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'France / China Sourced',
    displayOrder: 4,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  {
    id: 5,
    slug: 'china-direct-custom-industrial-sourcing',
    title: 'China Direct Sourcing & Personal Procurement Service',
    titleBn: 'চীন থেকে সরাসরি ইন্ডাস্ট্রিয়াল পার্টস ও মেশিন সোর্সিং সার্ভিস',
    modelNo: 'SYN-PROCURE-B2B',
    brand: 'Synapse Global Supply',
    category: 'Global Sourcing & Import',
    subCategory: 'Turnkey Procurement & QC',
    description: 'Dedicated on-ground technical procurement contractor based in China. We personally visit factories in Guangdong, Jiangsu, and Zhejiang to inspect quality, verify tolerances, negotiate direct manufacturer rates, and deliver machinery and obsolete components directly to your factory in Bangladesh.',
    descriptionBn: 'চীন থেকে বিশ্বস্ত ও মানসম্পন্ন ইন্ডাস্ট্রিয়াল মেশিনারি, রিপ্লেসমেন্ট পার্টস এবং ইলেকট্রিক্যাল ইকুইপমেন্ট সরাসরি ফ্যাক্টরি পরিদর্শনের মাধ্যমে দ্রুত ও নিরাপদে বাংলাদেশে আমদানির পূর্ণাঙ্গ সেবা।',
    specs: JSON.stringify({
      'Sourcing Hubs': 'Shenzhen, Dongguan, Ningbo, Wenzhou, Shanghai',
      'Services Included': 'Supplier Audit, Lab Inspection, Sample Testing, Customs & Freight',
      'Delivery Timeline': 'Air Cargo: 7-10 Days | Sea Freight: 25-35 Days',
      'Custom Solutions': 'Obsolete Parts Reproduction, Reverse Engineering, Bulk BOM Sourcing',
      'Doorstep Delivery': 'All Industrial Zones (Dhaka, Chittagong, Gazipur, Narayanganj, Bogura)'
    }),
    price: 0,
    priceType: 'quote',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://synapse-engneering.com/wp-content/uploads/2026/04/automation.png',
    additionalImages: JSON.stringify([]),
    featured: 1,
    stockStatus: 'Available on Request',
    originCountry: 'China / Global',
    displayOrder: 5,
    createdAt: '2026-09-01T00:00:00.000Z'
  }
];
