import { Product } from '@/db/schema';

// Curated authentic products for Synapse Engineering & Supply (Industrial B2B + Direct Consumer Gadgets)
export const INITIAL_PRODUCTS: Product[] = [
  // 1. Industrial Solar & Energy Storage
  {
    id: 1,
    slug: 'hithium-heroee-16-16kwh-lifepo4-battery-pack',
    title: 'HiTHIUM HeroEE 16 — 16kWh LiFePO₄ Portable Industrial Battery',
    titleBn: 'হাইথিয়াম হিরো-ইই ১৬ — ১৬ কিলোওয়াট-আওয়ার লিথিয়াম আয়ন ব্যাটারি',
    modelNo: 'HeroEE-16-51.2V-314Ah',
    brand: 'HiTHIUM',
    category: 'Solar & Power Solutions',
    subCategory: 'Lithium / LiFePO4 Energy Storage',
    description: 'Ultra-durable 16kWh LiFePO₄ energy storage system with 11,000+ cycle life. Engineered for factory backup, high-capacity hybrid solar systems, and zero-downtime industrial power continuity in Bangladesh. Equipped with intelligent smart-BMS supporting CAN/RS485 multi-inverter protocol.',
    descriptionBn: '১১,০০০+ সাইকেল লাইফ সমৃদ্ধ ১৬ কিলোওয়াট-আওয়ার হাইথিয়াম লিথিয়াম ফেরো ফসফেট ব্যাটারি প্যাক। ফ্যাক্টরি, কমার্শিয়াল প্রজেক্ট এবং হেভি ডিউটি সোলার পাওয়ার স্টোরেজের জন্য আদর্শ।',
    specs: JSON.stringify({
      'Rated Capacity': '16.08 kWh (51.2V 314Ah)',
      'Battery Chemistry': 'Grade-A LiFePO₄ (Lithium Iron Phosphate)',
      'Cycle Life': '≥ 11,000 Cycles @ 80% DOD (15-20 Years Duty)',
      'Max Current': '150A Continuous Charge / 200A Discharge',
      'Communication': 'CAN / RS485 / RS232 (Deye, Growatt, Megarevo)',
      'Warranty': '10 Years Manufacturer Warranty',
      'Origin': 'Xiamen, China (Direct Factory Dispatch)'
    }),
    price: 0,
    priceType: 'quote',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://synapse-engneering.com/wp-content/uploads/2026/03/HiTHIUM-HeroEE-16.png',
    additionalImages: JSON.stringify([
      'https://synapse-engneering.com/wp-content/uploads/2026/03/HiTHIUM-HeroEE-16-621x800.png'
    ]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'China',
    displayOrder: 1,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  // 2. Consumer Tech: High-Capacity Portable Power Station
  {
    id: 2,
    slug: 'synapse-powerhub-600w-portable-lifepo4-power-station',
    title: 'Synapse PowerHub 600W — Portable LiFePO₄ Power Station (Camping & Home Backup)',
    titleBn: 'সিন্যাপ্স পাওয়ারহাব ৬০০ ওয়াট — পোর্টেবল লিথিয়াম পাওয়ার স্টেশন',
    modelNo: 'SYN-PH600-LFP',
    brand: 'Synapse Tech Direct',
    category: 'Consumer Tech & Gadgets',
    subCategory: 'Portable Power & Chargers',
    description: 'High-density 512Wh LiFePO₄ portable power station with 600W pure sine wave AC output (1200W surge), 100W USB-C PD fast charging, and integrated LED light bar. Ideal for home load shedding, photography shoots, outdoor camping, and running laptops, TVs, and medical equipment.',
    descriptionBn: '৫১২ ওয়াট-আওয়ার পোর্টেবল লিথিয়াম ব্যাটারি পাওয়ার স্টেশন। লোডশেডিং, ট্রাভেল এবং আউটডোর কাজের জন্য ল্যাপটপ, ফ্যান ও জরুরি গ্যাজেট নিরবচ্ছিন্নভাবে চালানোর সম্পূর্ণ সমাধান।',
    specs: JSON.stringify({
      'Battery Capacity': '512Wh Grade-A LiFePO₄ (3,000+ Cycles to 80%)',
      'AC Output': '600W Pure Sine Wave (1200W Peak Surge, 230V 50Hz)',
      'USB-C Port': '100W Power Delivery (PD 3.0) Fast Charge',
      'Solar Charging Input': '12V-28V DC (Up to 200W MPPT Solar)',
      'Recharge Time': '0 to 80% in 55 minutes via Wall AC',
      'Weight': '6.2 kg with Ergonomic Carrying Handle',
      'Warranty': '2 Years Replacement Warranty'
    }),
    price: 34500,
    priceType: 'fixed',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80',
    additionalImages: JSON.stringify([]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'China',
    displayOrder: 2,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  // 3. Consumer Tech: 140W GaN Pro Multi-Port Desktop Charger
  {
    id: 3,
    slug: 'synapse-gan-140w-4port-fast-charger-pd31',
    title: 'Synapse 140W GaN Pro — 4-Port Ultra Fast Charger (MacBook Pro & Multi-Device)',
    titleBn: 'সিন্যাপ্স ১৪০ ওয়াট গ্যালিয়াম নাইট্রাইড (GaN) ৪-পোর্ট ফাস্ট চার্জার',
    modelNo: 'SYN-GAN140-PRO',
    brand: 'Synapse Tech Direct',
    category: 'Consumer Tech & Gadgets',
    subCategory: 'Charging & Cables',
    description: 'Next-generation Gallium Nitride (GaN III) 140W desktop fast charger with 3x USB-C and 1x USB-A ports. Features PD 3.1 protocol capable of charging a 16-inch MacBook Pro from 0 to 50% in just 28 minutes while simultaneously powering an iPhone, tablet, and earbuds.',
    descriptionBn: 'লেটেস্ট GaN ৩ প্রযুক্তিযুক্ত ১৪০ ওয়াট সুপারফাস্ট মাল্টি-পোর্ট চার্জার। একসাথে ম্যাকবুক, ল্যাপটপ, আইফোন ও অন্যান্য গ্যাজেট সম্পূর্ণ হিটিং ছাড়া দ্রুত চার্জ করার নিশ্চয়তা।',
    specs: JSON.stringify({
      'Total Output': '140W Max with Intelligent Power Allocation',
      'Ports': '3x USB-C (PD 3.1 / PPS), 1x USB-A (QC 4.0+)',
      'Single Port Max': 'USB-C1: Up to 140W (28V/5A)',
      'Protection': 'Over-temperature, Over-voltage, Short-circuit protection',
      'Compatibility': 'Apple M1/M2/M3 MacBook, Dell XPS, Samsung S24 Ultra, iPhone 15/16',
      'Size & Weight': '40% smaller than standard 140W brick (240g)'
    }),
    price: 4200,
    priceType: 'fixed',
    datasheetUrl: '',
    primaryImage: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    additionalImages: JSON.stringify([]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'China (Shenzhen Direct)',
    displayOrder: 3,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  // 4. Consumer Tech: Smart Home Zigbee 3.0 Energy Monitoring Gateway & Relay
  {
    id: 4,
    slug: 'tuya-zigbee3-smart-home-automation-hub-relay',
    title: 'Tuya Zigbee 3.0 Smart Home Gateway & 16A Energy Monitoring Relay Set',
    titleBn: 'তুয়া জিগবি ৩.০ স্মার্ট হোম গেটওয়ে ও পাওয়ার মনিটরিং রিলে কিট',
    modelNo: 'TY-ZIG3-HUB-KIT',
    brand: 'Tuya Smart Direct',
    category: 'Consumer Tech & Gadgets',
    subCategory: 'Smart Home & Automation',
    description: 'Complete DIY smart home starter kit including 1x Zigbee 3.0 Universal Mesh Gateway and 3x 16A Mini Relays with real-time kWh power measurement. Control lights, ACs, water pumps, and appliances from anywhere using Smart Life app, Google Assistant, or Alexa with zero lag.',
    descriptionBn: 'স্মার্ট হোম অটোমেশন গেটওয়ে ও ১৬ অ্যাম্পিয়ার পাওয়ার মনিটরিং রিলে। মোবাইল অ্যাপ দিয়ে বাসার লাইট, এসি, ও ওয়াটার পাম্প কন্ট্রোল এবং বিদ্যুৎ খরচের রিয়েল-টাইম হিসাব দেখুন।',
    specs: JSON.stringify({
      'Protocol': 'Zigbee 3.0 + Wi-Fi 2.4GHz Mesh (Up to 128 devices)',
      'Max Load per Relay': '16A / 3680W (AC 100-240V 50/60Hz)',
      'Features': 'App Scheduling, Voice Control, Real-Time kWh Metering, Power-off Memory',
      'App Support': 'Smart Life / Tuya Smart (iOS & Android)',
      'Voice Assistants': 'Amazon Alexa, Google Home Assistant, Siri Shortcuts'
    }),
    price: 3850,
    priceType: 'fixed',
    datasheetUrl: '',
    primaryImage: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
    additionalImages: JSON.stringify([]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'China',
    displayOrder: 4,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  // 5. Industrial Automation: Siemens SIMATIC S7-1500 Analog Output Module
  {
    id: 5,
    slug: 'siemens-s7-1500-6es7532-5hd00-0ab0-analog-output',
    title: 'Siemens SIMATIC S7-1500 6ES7532-5HD00-0AB0 Analog Output Module',
    titleBn: 'সিমেন্স এস৭-১৫০০ অ্যানালগ আউটপুট মডিউল',
    modelNo: '6ES7532-5HD00-0AB0',
    brand: 'Siemens',
    category: 'Industrial Automation',
    subCategory: 'PLC Systems & I/O Modules',
    description: 'Original Siemens SIMATIC S7-1500 Analog Output Module with 4 channels for voltage (±10V, 1..5V, 0..10V) and current (±20mA, 0/4..20mA). 16-bit resolution with diagnostics and parameter alarms. Directly sourced and guaranteed authentic from certified distributors in China.',
    descriptionBn: 'অরিজিনাল সিমেন্স S7-1500 অ্যানালগ আউটপুট মডিউল (৪ চ্যানেল, ১৬-বিট রেজোলিউশন)। ইন্ডাস্ট্রিয়াল প্রসেস কন্ট্রোল ও ফ্যাক্টরি অটোমেশনের জন্য শতভাগ জেনুইন ইকুইপমেন্ট।',
    specs: JSON.stringify({
      'Channels': '4 Analog Outputs (Voltage / Current)',
      'Resolution': '16 Bit',
      'Output Ranges Voltage': '±10V, 1-5V, 0-10V',
      'Output Ranges Current': '±20mA, 0-20mA, 4-20mA',
      'Diagnostics': 'Wire break, short circuit, overflow/underflow alarms',
      'Mounting': 'S7-1500 DIN Rail Standard',
      'Authenticity': '100% Genuine with Original Siemens Seal & Serial'
    }),
    price: 0,
    priceType: 'quote',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://synapse-engneering.com/wp-content/uploads/2026/05/siemens-s7-1500-6es7532-5hd00-0ab0-analog-output-276x355.webp',
    additionalImages: JSON.stringify([]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'Germany / China Direct',
    displayOrder: 5,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  // 6. Industrial Automation: Schneider Electric TeSys K LC1K06105P7 Contactor
  {
    id: 6,
    slug: 'schneider-lc1k06105p7-contactor-6a-230v',
    title: 'Schneider Electric TeSys K LC1K06105P7 Contactor 6A 230V',
    titleBn: 'স্নাইডার ইলেকট্রিক টেসিস কে কন্টাক্টর ৬ অ্যাম্পিয়ার ২৩০ ভোল্ট',
    modelNo: 'LC1K06105P7',
    brand: 'Schneider Electric',
    category: 'Industrial Automation',
    subCategory: 'Contactors & Motor Starters',
    description: 'Compact 3-pole TeSys K contactor rated 6A (AC-3, 440V, 2.2kW) with 230V AC control coil and 1 NO instantaneous auxiliary contact. Ideal for motor control, HVAC equipment, packaging lines, and industrial control panels.',
    descriptionBn: 'স্নাইডার ইলেকট্রিক টেসিস কে ৩-পোল কন্টাক্টর (৬ অ্যাম্পিয়ার, ২৩০V কয়েল)। কন্ট্রোল প্যানেল, মোটর কন্ট্রোল ও ইন্ডাস্ট্রিয়াল সুইচকন্ট্রোলের জন্য দীর্ঘস্থায়ী উপাদান।',
    specs: JSON.stringify({
      'Poles': '3P (3 NO Main Contacts)',
      'Rated Current': '6A (AC-3 @ 440V)',
      'Motor Power': '2.2 kW @ 380/415V AC',
      'Control Circuit Voltage': '230V AC 50/60 Hz',
      'Auxiliary Contacts': '1 NO (Normally Open)',
      'Mechanical Durability': '10 Million Cycles'
    }),
    price: 0,
    priceType: 'quote',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://synapse-engneering.com/wp-content/uploads/2026/05/lc1k1210m7-276x355.webp',
    additionalImages: JSON.stringify([]),
    featured: 1,
    stockStatus: 'In Stock',
    originCountry: 'France / China Sourced',
    displayOrder: 6,
    createdAt: '2026-09-01T00:00:00.000Z'
  },
  // 7. Direct China Procurement & QC Concierge Service
  {
    id: 7,
    slug: 'china-direct-custom-industrial-sourcing',
    title: 'Personal China Sourcing Concierge (Factory Visit, Video QC & Direct Import)',
    titleBn: 'চীন থেকে সরাসরি পার্সোনাল সোর্সিং ও ফ্যাক্টরি পরিদর্শন সার্ভিস',
    modelNo: 'SYN-SOURCING-CONCIERGE',
    brand: 'Synapse Global Desk',
    category: 'Global Sourcing & Import',
    subCategory: 'Turnkey Procurement & QC',
    description: 'Have a specific machine, production line, or bulk consumer gadget you need from China? Our on-ground team in Guangdong personally visits the manufacturing plant, sends you live video verification, negotiates direct wholesale rates, and handles complete customs and air/sea delivery to Bangladesh.',
    descriptionBn: 'চীন থেকে নির্দিষ্ট কোনো মেশিনারি বা গ্যাজেট আমদানির জন্য আমাদের অন-গ্রাউন্ড প্রতিনিধি সরাসরি ফ্যাক্টরি পরিদর্শন করে ভিডিও পাঠিয়ে কোয়ালিটি নিশ্চিত করে বাংলাদেশে ডেলিভারির ব্যবস্থা করে।',
    specs: JSON.stringify({
      'On-Ground Hubs': 'Shenzhen, Guangzhou, Dongguan, Yiwu, Ningbo',
      'Services Included': 'Physical Factory Inspection, Video QC, Sample Testing, Customs Clearance',
      'Transit Options': 'Air Cargo (7-10 Days) | Sea Container (25-35 Days)',
      'Assistance': '1-on-1 WhatsApp Support with English & Bengali translation'
    }),
    price: 0,
    priceType: 'quote',
    datasheetUrl: 'https://synapse-engneering.com/wp-content/uploads/2026/04/Synapse-Engineering-Company-Profile.pdf',
    primaryImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    additionalImages: JSON.stringify([]),
    featured: 1,
    stockStatus: 'Available on Request',
    originCountry: 'China / Global',
    displayOrder: 7,
    createdAt: '2026-09-01T00:00:00.000Z'
  }
];
